<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>ezgetBMCIP.ico</ApplicationIcon>
    <AssemblyName>ezgetBMCIP</AssemblyName>
    <RootNamespace>EzGetBmcIp</RootNamespace>
    <Version>1.2.0</Version>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <DefaultItemExcludes>$(DefaultItemExcludes);artifacts\**</DefaultItemExcludes>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="WPF-UI" Version="4.*" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="ezgetBMCIP.ico" />
    <Compile Remove="bin\**" />
    <Compile Remove="obj\**" />
    <Compile Remove="artifacts\**" />
    <Compile Remove="publish-vscode\**" />
  </ItemGroup>
</Project>
